In [1]:
import numpy as np
import pandas as pd


In [3]:
data = {"grammer":['Python', 'C', 'Java', 'GO', np.NaN, 'SQL', 'PHP', 'Python'],
       "score":[1.0, 2.0, np.NaN, 4.0, 5.0, 6.0, 7.0, 10.0]}
df = pd.DataFrame(data)
print(df)

  grammer  score
0  Python    1.0
1       C    2.0
2    Java    NaN
3      GO    4.0
4     NaN    5.0
5     SQL    6.0
6     PHP    7.0
7  Python   10.0


In [6]:
# 提取含有Python的行
## 1
df[df['grammer'] == 'Python']

## 2
results = df['grammer'].str.contains('Python')
print(results)
results.fillna(value=False, inplace=True)
df[results]

0     True
1    False
2    False
3    False
4      NaN
5    False
6    False
7     True
Name: grammer, dtype: object


grammer  score
0  Python    1.0
7  Python   10.0

In [9]:
# 输出列名
df.columns


Index(['grammer', 'popularity'], dtype='object')

In [8]:
# 修改列名
df.rename(columns={'score':'popularity'}, inplace=True)

In [11]:
# 统计列中次数
df['grammer'].value_counts()

grammer
Python    2
C         1
Java      1
GO        1
SQL       1
PHP       1
Name: count, dtype: int64

In [13]:
# 空值填充  上下值的平均值
df['popularity'] = df['popularity'].fillna(df['popularity'].interpolate())
print(df)

  grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SQL         6.0
6     PHP         7.0
7  Python        10.0


In [14]:
df[df['popularity'] > 3]

grammer  popularity
3      GO         4.0
4     NaN         5.0
5     SQL         6.0
6     PHP         7.0
7  Python        10.0

In [15]:
# 去除重复值
df.drop_duplicates(['grammer'])

grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SQL         6.0
6     PHP         7.0

In [16]:
# 计算平均值
df['popularity'].mean()

4.75

In [17]:
# 将某列转化成列表
df['grammer'].to_list()

['Python', 'C', 'Java', 'GO', nan, 'SQL', 'PHP', 'Python']

In [18]:
# 保存为csv
df.to_csv("test.csv")

In [20]:
# 查看行列数
df.shape

(8, 2)

In [25]:
# 交换两列位置
## 1
# temp = df['popularity']
# df.drop(labels=['popularity'], axis=1, inplace=True)
# df.insert(0, 'popularity', temp) 
# df

## 2
cols = df.columns[[1, 0]]
# print(cols)
df = df[cols]
df

grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SQL         6.0
6     PHP         7.0
7  Python        10.0

In [26]:
# 提取某列最大值所在的行
df[df['popularity'] == df['popularity'].max()]

grammer  popularity
7  Python        10.0

In [27]:
# 随机生成随机整数
np.random.randint(0, 100, 20)

array([11, 71, 48, 46, 59, 18,  0, 29, 87, 43,  9, 84, 40, 79, 94, 38, 19,
       46, 98, 11])

In [28]:
# 生成20个固定步长的数组
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [29]:
# 正态分布
np.random.normal(0, 1, 20)

array([ 0.21742331, -0.76196915,  0.78216341,  1.11000926, -1.10171919,
       -0.10587389,  1.55352314,  1.62061218, -0.30768583, -0.43173618,
       -1.52480215,  0.19074709, -0.54383496,  1.81113292,  1.10602152,
        0.13997988,  2.44438854, -0.43050699,  0.29783524,  0.90831258])

In [34]:
# 提取score列中可以整除5的数字位置
data = {"grammer":['Python', 'C', 'Java', 'GO', 'css', 'SQL', 'PHP', 'Python'],
       "score":[1.0, 2.0, 6.0, 4.0, 5.0, 6.0, 7.0, 10.0]}
df = pd.DataFrame(data)
# np.argwhere() 函数查找布尔数组中为 True 的元素的索引

array([[4],
       [7]], dtype=int64)

In [37]:
# 查找两列值相等的索引 
df['cycle'] = [2.0, 3.0, 6.0, 3.0, 5.0, 2.0, 7.0, 5.0]
# #方法一：值相等
# df[df['score'] == df['cycle']].index

## 2
np.where(df.score == df.cycle)

(array([2, 4, 6], dtype=int64),)

In [40]:
# 查找第一列局部最大值的位置 numpy.sign()
#思路：查找比它前一个和后一个数字都大数字
tem = np.diff(np.sign(np.diff(df['score'])))
print(tem)
np.where(tem == -2)[0] + 1


[ 0. -2.  2.  0.  0.  0.]


array([2], dtype=int64)

In [44]:
df['cycle']
# np.ones(3)

0    2.0
1    3.0
2    6.0
3    3.0
4    5.0
5    2.0
6    7.0
7    5.0
Name: cycle, dtype: float64

In [41]:
# 计算移动平均值
np.convolve(df['cycle'], np.ones(3)/3, mode='valid')

array([3.66666667, 4.        , 4.66666667, 3.33333333, 4.66666667,
       4.66666667])

In [47]:
# 计算两列欧式距离：Numpy.linalg.norm()
#方法一：公式法
import math as mt
mt.sqrt(sum((df['score']-df['cycle'])**2))
 
#方法二：numpy函数
np.linalg.norm(df['score'] - df['cycle'])

6.6332495807108

In [78]:
print(df['score'])
print(df['score'].argsort())
df['score'].argsort()[len(df)-3]

0     1.0
1     2.0
2     6.0
3     4.0
4     5.0
5     6.0
6     7.0
7    10.0
Name: score, dtype: float64
0    0
1    1
2    3
3    4
4    2
5    5
6    6
7    7
Name: score, dtype: int64


5

In [79]:
# 查找某列数据中第三大值的行号：Numpy.argsort()
#方法一：
df['score'].argsort()[::-1][len(df)-3]
#注：argsort() -- 从小到大排, 输出索引；[[::-1]]倒序输出 -- 即为从大到小排；
#方法二：先进行倒序排序，然后重置索引，取第三行第一列即为第3大值的行号
# df['score'].sort_values(ascending=False).reset_index().iloc[2,0]

5

In [69]:
print(df['score'].sort_values(ascending=False).reset_index())
df['score'].sort_values(ascending=False).reset_index().iloc[2,0]  # 第三行第一列的元素

   index  score
0      7   10.0
1      6    7.0
2      2    6.0
3      5    6.0
4      4    5.0
5      3    4.0
6      1    2.0
7      0    1.0


2

## 作业


In [110]:
data = {'Id': [202001, 202002, 202003, 202004, 202005, 202006, 202007, 202008, 202009, 202010], 
'Chinese': [98, 67, 84, 88, 78, 90, 93, 75, 82, 87], 'Math': [92, 80, 73, 76, 88, 78, 90, 82, 77, 69],'English': [88, 79, 90, 73, 79, 83, 81, 91, 71, 78]}
df = pd.DataFrame(data)
print(df)

       Id  Chinese  Math  English
0  202001       98    92       88
1  202002       67    80       79
2  202003       84    73       90
3  202004       88    76       73
4  202005       78    88       79
5  202006       90    78       83
6  202007       93    90       81
7  202008       75    82       91
8  202009       82    77       71
9  202010       87    69       78


In [111]:
# 总成绩
df['SumScore'] = df['Chinese'] + df['English'] + df['Math']
print(df)

       Id  Chinese  Math  English  SumScore
0  202001       98    92       88       278
1  202002       67    80       79       226
2  202003       84    73       90       247
3  202004       88    76       73       237
4  202005       78    88       79       245
5  202006       90    78       83       251
6  202007       93    90       81       264
7  202008       75    82       91       248
8  202009       82    77       71       230
9  202010       87    69       78       234


In [114]:
df['MeanScore'] = df[['Chinese', 'Math', 'English']].mean(axis=1).astype(int)
df['MaxScore'] = df[['Chinese', 'Math', 'English']].max(axis=1)
df['MaxScore'] = df[['Chinese', 'Math', 'English']].max(axis=1)
df['MinScore'] = df[['Chinese', 'Math', 'English']].min(axis=1)
df['PtpScore'] = df['MaxScore'] - df['MinScore']
df['VarScore'] = df[['Chinese', 'Math', 'English']].var(axis=1, ddof=0).astype(int) # ddof=0 计算总体标准差

print(df)

# 计算一组数据的方差，需要注意的是：numpy中的方差叫总体方差，pandas中的方差叫样本方差

# 标准差（或方差）分为 总体标准差（方差）和 样本标准差（方差）
# 前者分母为n，右偏的；后者分母为n-1，是无偏的
# pandas里是算无偏的；numpy里是有偏的

       Id  Chinese  Math  English  SumScore  MeanScore  MaxScore  MinScore  \
0  202001       98    92       88       278         92        98        88   
1  202002       67    80       79       226         75        80        67   
2  202003       84    73       90       247         82        90        73   
3  202004       88    76       73       237         79        88        73   
4  202005       78    88       79       245         81        88        78   
5  202006       90    78       83       251         83        90        78   
6  202007       93    90       81       264         88        93        81   
7  202008       75    82       91       248         82        91        75   
8  202009       82    77       71       230         76        82        71   
9  202010       87    69       78       234         78        87        69   

   PtpScore  VarScore  
0        10        16  
1        13        34  
2        17        49  
3        15        42  
4        10        20

In [104]:
np.var([67, 80, 79])

34.88888888888889