In [2]:
import numpy as np
np.__version__

'1.24.3'

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# 4. 如何找到任何一个数组的内存大小？
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


8

In [ ]:
# 5. 如何从命令行得到numpy中add函数的说明文档? (★☆☆)
np.info(np.add)

In [15]:
# 8. 反转一个向量(第一个元素变为最后一个) (★☆☆)
z = np.arange(10, 50)
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [20]:
# 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 
np.nonzero([1,2,0, 0, 3, 0])

(array([0, 1, 4], dtype=int64),)

In [21]:
# 15. 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


这一行使用np.pad函数对矩阵Z进行填充。参数解释如下：

pad_width=1：表示在矩阵的边缘填充一层宽度为1的零。
mode='constant'：表示使用常数填充模式，即填充指定常数值。
constant_values=0：表示使用0作为填充的常数值。

In [22]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [27]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [31]:
# 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆)
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [32]:
# 19. 创建一个8x8 的矩阵，并且设置成棋盘样式 (★☆☆)
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


np.unravel_index 函数用于根据一个平铺索引（flattened index）和一个多维数组的形状，返回该平铺索引对应的多维索引（坐标）。

In [33]:
# 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


In [3]:
# 21. 用tile函数去创建一个 8x8的棋盘样式矩阵(★☆☆)
# np.tile(..., (4, 4)) 使用 np.tile 函数将这个2x2的数组在行和列的方向上分别重复4次，形成了一个4x4的数组。
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
print(sum(range(5),-1))  
from numpy import *  
print(sum(range(5),-1))

9
10


In [6]:
# 30. 如何找到两个数组中的共同元素? (★☆☆)
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 3 4]


In [7]:
# 33. 如何得到昨天，今天，明天的日期? (★☆☆)
# np.timedelta64(1, 'D')：创建一个 numpy timedelta64 对象，表示1天的时间间隔。
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2023-12-07
Today is 2023-12-08
Tomorrow is 2023-12-09


In [20]:
# 多个日期
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [23]:
# 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)? (★★☆)
A = np.ones(3)*1
# print(A)
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

[1. 1. 1.]


array([-1.5, -1.5, -1.5])

In [24]:
# 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 (★★☆)
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [25]:
def generate():
    for x in range(10):
        yield x
        # np.fromiter：该函数从一个可迭代对象中创建一个新的一维数组。
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [26]:
# 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆)
# 这段代码使用 NumPy 的 linspace 函数创建了一个包含 0 到 1 之间的均匀间隔的浮点数数组，并通过 endpoint=False 参数排除了终点。然后使用切片 [1:] 选择了除第一个元素之外的所有元素。让我们逐步解释这段代码：
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [28]:
# np.sum(Z)，但 np.add.reduce 是一个更底层的函数，专门用于累加操作。
Z = np.arange(10)
np.add.reduce(Z)

45

In [29]:
# 42. 对于两个随机数组A和B，检查它们是否相等(★★☆)
# (提示: np.allclose, np.array_equal)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [31]:
# 方法2
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


In [32]:
# 43. 创建一个只读数组(read-only) (★★☆)
# (提示: flags.writeable)
Z = np.zeros(10)  
Z.flags.writeable = False  
Z[0] = 1 

ValueError: assignment destination is read-only

In [34]:
# 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式(★★☆)
# (hint: np.sqrt, np.arctan2)
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[1.02683001 1.00536979 0.49383124 1.07269424 0.90238898 0.4353329
 1.22619929 0.83972888 1.30153002 0.98768776]
[0.43136362 0.8233051  0.85002841 0.53188489 0.48276253 0.19034045
 0.64753585 0.07088061 0.73909917 1.25711594]


In [47]:
# 45. 创建一个长度为10的向量，并将向量中最大值替换为1 (★★☆)
# (提示: argmax)
Z = np.random.random(10)
# Z.argmax() #  返回最大值索引
Z[Z.argmax()] = 1
print (Z)


[0.60372618 0.12769475 0.51660074 1.         0.81046886 0.4327457
 0.85279168 0.509434   0.58330727 0.58090316]


In [48]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [55]:
# 59. 如何通过第n列对一个数组进行排序? (★★☆)
# (提示: argsort)
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[9 2 1]
 [4 4 2]
 [4 7 8]]
[[9 2 1]
 [4 4 2]
 [4 7 8]]
